# Generated by Django 4.2 on 2023-04-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelopia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='currency',
            field=models.IntegerField(),
        ),
    ]
