# Generated by Django 4.2 on 2023-04-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelopia', '0002_alter_person_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravellerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('destination_country', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('budget_per_person', models.IntegerField()),
                ('number_of_traveller', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
